
query_strategy: adv_deepfool
query_strategy_kwargs:
  batch_size: 48
  unlabeled_subset_size: 64000
n_query_ratio: 0.05
labeled_split_ratio: 0.10
n_rounds: 10
class_imbalance: False
n_classes_removed: 2
reset_model: false
al_seed: 0